#############################################################################
# Makefile for building: DentistaIS
# Generated by qmake (2.01a) (Qt 4.8.5) on: mié dic 3 13:36:16 2014
# Project:  DentistaIS.pro
# Template: app
# Command: /usr/local/opt/Qt-4.8.5/bin/qmake -o Makefile DentistaIS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/opt/Qt-4.8.5/mkspecs/linux-g++ -I. -I/usr/local/opt/Qt-4.8.5/include/QtCore -I/usr/local/opt/Qt-4.8.5/include/QtGui -I/usr/local/opt/Qt-4.8.5/include -I. -Iclinica -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/opt/Qt-4.8.5/lib
LIBS          = $(SUBLIBS)  -L/usr/local/opt/Qt-4.8.5/lib -lQtGui -L/usr/local/X11R7/lib -L/usr/local/opt/Qt-4.8.5/lib -L/usr/X11R6/lib -lQtCore -ldl -lpthread
AR            = ar cqs
RANLIB        =
QMAKE         = /usr/local/opt/Qt-4.8.5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = interfaz.cpp \
		main.cpp \
		clinica/agenda.cpp \
		clinica/paciente.cpp
OBJECTS       = interfaz.o \
		main.o \
		agenda.o \
		paciente.o
DIST          = /usr/local/opt/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/linux.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/opt/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/release.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/shared.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/include_source_dir.prf \
		DentistaIS.pro
QMAKE_TARGET  = DentistaIS
DESTDIR       =
TARGET        = DentistaIS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DentistaIS.pro  /usr/local/opt/Qt-4.8.5/mkspecs/linux-g++/qmake.conf /usr/local/opt/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/linux.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/opt/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/opt/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/release.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/shared.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/opt/Qt-4.8.5/mkspecs/features/include_source_dir.prf \
		/usr/local/opt/Qt-4.8.5/lib/libQtGui.prl \
		/usr/local/opt/Qt-4.8.5/lib/libQtCore.prl
	$(QMAKE) -o Makefile DentistaIS.pro
/usr/local/opt/Qt-4.8.5/mkspecs/common/unix.conf:
/usr/local/opt/Qt-4.8.5/mkspecs/common/linux.conf:
/usr/local/opt/Qt-4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/opt/Qt-4.8.5/mkspecs/common/gcc-base-unix.conf:
/usr/local/opt/Qt-4.8.5/mkspecs/common/g++-base.conf:
/usr/local/opt/Qt-4.8.5/mkspecs/common/g++-unix.conf:
/usr/local/opt/Qt-4.8.5/mkspecs/qconfig.pri:
/usr/local/opt/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri:
/usr/local/opt/Qt-4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/qt_config.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/default_pre.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/release.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/default_post.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/shared.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/warn_on.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/qt.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/moc.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/resources.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/uic.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/yacc.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/lex.prf:
/usr/local/opt/Qt-4.8.5/mkspecs/features/include_source_dir.prf:
/usr/local/opt/Qt-4.8.5/lib/libQtGui.prl:
/usr/local/opt/Qt-4.8.5/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile DentistaIS.pro

dist:
	@$(CHK_DIR_EXISTS) .tmp/DentistaIS1.0.0 || $(MKDIR) .tmp/DentistaIS1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DentistaIS1.0.0/ && $(COPY_FILE) --parents interfaz.h clinica/agenda.h clinica/paciente.h .tmp/DentistaIS1.0.0/ && $(COPY_FILE) --parents interfaz.cpp main.cpp clinica/agenda.cpp clinica/paciente.cpp .tmp/DentistaIS1.0.0/ && (cd `dirname .tmp/DentistaIS1.0.0` && $(TAR) DentistaIS1.0.0.tar DentistaIS1.0.0 && $(COMPRESS) DentistaIS1.0.0.tar) && $(MOVE) `dirname .tmp/DentistaIS1.0.0`/DentistaIS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DentistaIS1.0.0


clean:compiler_clean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean:

####### Compile

interfaz.o: interfaz.cpp interfaz.h \
		clinica/agenda.h \
		clinica/paciente.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interfaz.o interfaz.cpp

main.o: main.cpp interfaz.h \
		clinica/agenda.h \
		clinica/paciente.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

agenda.o: clinica/agenda.cpp clinica/agenda.h \
		clinica/paciente.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agenda.o clinica/agenda.cpp

paciente.o: clinica/paciente.cpp clinica/paciente.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paciente.o clinica/paciente.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

